[versions]
agp = "8.7.2"
kotlin = "2.0.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.1"
activityCompose = "1.10.1"
composeBom = "2024.04.01"
jetbrainsKotlinJvm = "1.9.24"
appcompat = "1.7.1"
material = "1.12.0"
jetbrainsKotlinJvmVersion = "2.0.0"

[libraries]

[plugins]
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

